export const ROUTES = {
  PUBLIC: {
    LANDING: '/',
    ABOUT: '/about',
    CONTACT: '/contact',
    HELP: '/help',
    PRIVACY: '/privacy',
    TERMS: '/terms',
    REFUND: '/refund',
    SHIPPING: '/shipping',
  },
  AUTH: {
    SIGNIN: '/signin',
    SIGNUP: '/signup',
    VERIFY_EMAIL: '/verify-email',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
  },
  PROTECTED: {
    DASHBOARD: '/dashboard',
    SETTINGS: '/settings',
    PROFILE: '/settings',
    HISTORY: '/history',
    SUBMIT_IDEA: '/submit-idea',
    IDEA_RESULTS: '/idea/:id',
    SAVED_IDEAS: '/saved-ideas',
    PITCH_DECK: '/pitch-deck/:id',
    COLLABORATIVE_PITCH: '/collaborative-pitch/:id',
    CANVAS: '/canvas/:id',
    INVESTORS: '/investors',
    INVESTOR_MATCHING: '/investor-matching',
    COMPETITORS: '/competitors',
    COMPETITOR_DETAIL: '/competitors/:id',
    PITCH_SIMULATOR: '/pitch-simulator',
    PITCH_SIMULATOR_DETAIL: '/pitch-simulator/:id',
    CREDITS: '/credits',
    PAYMENT_SUCCESS: '/payment-success',
    MARKET_RESEARCH: '/market-research',
  },
} as const;
